title: sgzks 的博客
description: 我的 Jekyll 静态博客实验网站
author:
  name: 学生姓名
  email: student@example.com
  github: https://github.com/sgzks

baseurl: ""
url: "https://sgzks.github.io"
github_username: sgzks
permalink: /posts/:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "学生姓名"

plugins:
  - jekyll-feed
  - jekyll-sitemap